/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as MiniGamesRouteImport } from './routes/mini-games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebProjectsIndexRouteImport } from './routes/web-projects/index'
import { Route as UiuxIndexRouteImport } from './routes/uiux/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as AiIndexRouteImport } from './routes/ai/index'
import { Route as ExperimentsBookingSimulationRouteImport } from './routes/experiments/booking-simulation'
import { Route as ExperimentsBookingPlatformRouteImport } from './routes/experiments/booking-platform'
import { Route as ExperimentsBookingPlatformIndexRouteImport } from './routes/experiments/booking-platform/index'
import { Route as ToolsSlugProcessRouteImport } from './routes/tools/$slug/process'
import { Route as ToolsSlugLaunchRouteImport } from './routes/tools/$slug/launch'
import { Route as ExperimentsBookingSimulationAppRouteImport } from './routes/experiments/booking-simulation/app'
import { Route as ExperimentsBookingPlatformSuccessRouteImport } from './routes/experiments/booking-platform/success'
import { Route as ExperimentsBookingPlatformAppRouteImport } from './routes/experiments/booking-platform/app'
import { Route as AiAiChatEngineAppRouteImport } from './routes/ai/ai-chat-engine/app'
import { Route as AiSlugProcessRouteImport } from './routes/ai/$slug/process'
import { Route as AiSlugExploreRouteImport } from './routes/ai/$slug/explore'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniGamesRoute = MiniGamesRouteImport.update({
  id: '/mini-games',
  path: '/mini-games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebProjectsIndexRoute = WebProjectsIndexRouteImport.update({
  id: '/web-projects/',
  path: '/web-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiuxIndexRoute = UiuxIndexRouteImport.update({
  id: '/uiux/',
  path: '/uiux/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsBookingSimulationRoute =
  ExperimentsBookingSimulationRouteImport.update({
    id: '/experiments/booking-simulation',
    path: '/experiments/booking-simulation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperimentsBookingPlatformRoute =
  ExperimentsBookingPlatformRouteImport.update({
    id: '/experiments/booking-platform',
    path: '/experiments/booking-platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperimentsBookingPlatformIndexRoute =
  ExperimentsBookingPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExperimentsBookingPlatformRoute,
  } as any)
const ToolsSlugProcessRoute = ToolsSlugProcessRouteImport.update({
  id: '/tools/$slug/process',
  path: '/tools/$slug/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugLaunchRoute = ToolsSlugLaunchRouteImport.update({
  id: '/tools/$slug/launch',
  path: '/tools/$slug/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsBookingSimulationAppRoute =
  ExperimentsBookingSimulationAppRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => ExperimentsBookingSimulationRoute,
  } as any)
const ExperimentsBookingPlatformSuccessRoute =
  ExperimentsBookingPlatformSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => ExperimentsBookingPlatformRoute,
  } as any)
const ExperimentsBookingPlatformAppRoute =
  ExperimentsBookingPlatformAppRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => ExperimentsBookingPlatformRoute,
  } as any)
const AiAiChatEngineAppRoute = AiAiChatEngineAppRouteImport.update({
  id: '/ai/ai-chat-engine/app',
  path: '/ai/ai-chat-engine/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSlugProcessRoute = AiSlugProcessRouteImport.update({
  id: '/ai/$slug/process',
  path: '/ai/$slug/process',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSlugExploreRoute = AiSlugExploreRouteImport.update({
  id: '/ai/$slug/explore',
  path: '/ai/$slug/explore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mini-games': typeof MiniGamesRoute
  '/systems': typeof SystemsRoute
  '/experiments/booking-platform': typeof ExperimentsBookingPlatformRouteWithChildren
  '/experiments/booking-simulation': typeof ExperimentsBookingSimulationRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/uiux/': typeof UiuxIndexRoute
  '/web-projects/': typeof WebProjectsIndexRoute
  '/ai/$slug/explore': typeof AiSlugExploreRoute
  '/ai/$slug/process': typeof AiSlugProcessRoute
  '/ai/ai-chat-engine/app': typeof AiAiChatEngineAppRoute
  '/experiments/booking-platform/app': typeof ExperimentsBookingPlatformAppRoute
  '/experiments/booking-platform/success': typeof ExperimentsBookingPlatformSuccessRoute
  '/experiments/booking-simulation/app': typeof ExperimentsBookingSimulationAppRoute
  '/tools/$slug/launch': typeof ToolsSlugLaunchRoute
  '/tools/$slug/process': typeof ToolsSlugProcessRoute
  '/experiments/booking-platform/': typeof ExperimentsBookingPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mini-games': typeof MiniGamesRoute
  '/systems': typeof SystemsRoute
  '/experiments/booking-simulation': typeof ExperimentsBookingSimulationRouteWithChildren
  '/ai': typeof AiIndexRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/uiux': typeof UiuxIndexRoute
  '/web-projects': typeof WebProjectsIndexRoute
  '/ai/$slug/explore': typeof AiSlugExploreRoute
  '/ai/$slug/process': typeof AiSlugProcessRoute
  '/ai/ai-chat-engine/app': typeof AiAiChatEngineAppRoute
  '/experiments/booking-platform/app': typeof ExperimentsBookingPlatformAppRoute
  '/experiments/booking-platform/success': typeof ExperimentsBookingPlatformSuccessRoute
  '/experiments/booking-simulation/app': typeof ExperimentsBookingSimulationAppRoute
  '/tools/$slug/launch': typeof ToolsSlugLaunchRoute
  '/tools/$slug/process': typeof ToolsSlugProcessRoute
  '/experiments/booking-platform': typeof ExperimentsBookingPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mini-games': typeof MiniGamesRoute
  '/systems': typeof SystemsRoute
  '/experiments/booking-platform': typeof ExperimentsBookingPlatformRouteWithChildren
  '/experiments/booking-simulation': typeof ExperimentsBookingSimulationRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/uiux/': typeof UiuxIndexRoute
  '/web-projects/': typeof WebProjectsIndexRoute
  '/ai/$slug/explore': typeof AiSlugExploreRoute
  '/ai/$slug/process': typeof AiSlugProcessRoute
  '/ai/ai-chat-engine/app': typeof AiAiChatEngineAppRoute
  '/experiments/booking-platform/app': typeof ExperimentsBookingPlatformAppRoute
  '/experiments/booking-platform/success': typeof ExperimentsBookingPlatformSuccessRoute
  '/experiments/booking-simulation/app': typeof ExperimentsBookingSimulationAppRoute
  '/tools/$slug/launch': typeof ToolsSlugLaunchRoute
  '/tools/$slug/process': typeof ToolsSlugProcessRoute
  '/experiments/booking-platform/': typeof ExperimentsBookingPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mini-games'
    | '/systems'
    | '/experiments/booking-platform'
    | '/experiments/booking-simulation'
    | '/ai/'
    | '/experiments/'
    | '/tools/'
    | '/uiux/'
    | '/web-projects/'
    | '/ai/$slug/explore'
    | '/ai/$slug/process'
    | '/ai/ai-chat-engine/app'
    | '/experiments/booking-platform/app'
    | '/experiments/booking-platform/success'
    | '/experiments/booking-simulation/app'
    | '/tools/$slug/launch'
    | '/tools/$slug/process'
    | '/experiments/booking-platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mini-games'
    | '/systems'
    | '/experiments/booking-simulation'
    | '/ai'
    | '/experiments'
    | '/tools'
    | '/uiux'
    | '/web-projects'
    | '/ai/$slug/explore'
    | '/ai/$slug/process'
    | '/ai/ai-chat-engine/app'
    | '/experiments/booking-platform/app'
    | '/experiments/booking-platform/success'
    | '/experiments/booking-simulation/app'
    | '/tools/$slug/launch'
    | '/tools/$slug/process'
    | '/experiments/booking-platform'
  id:
    | '__root__'
    | '/'
    | '/mini-games'
    | '/systems'
    | '/experiments/booking-platform'
    | '/experiments/booking-simulation'
    | '/ai/'
    | '/experiments/'
    | '/tools/'
    | '/uiux/'
    | '/web-projects/'
    | '/ai/$slug/explore'
    | '/ai/$slug/process'
    | '/ai/ai-chat-engine/app'
    | '/experiments/booking-platform/app'
    | '/experiments/booking-platform/success'
    | '/experiments/booking-simulation/app'
    | '/tools/$slug/launch'
    | '/tools/$slug/process'
    | '/experiments/booking-platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiniGamesRoute: typeof MiniGamesRoute
  SystemsRoute: typeof SystemsRoute
  ExperimentsBookingPlatformRoute: typeof ExperimentsBookingPlatformRouteWithChildren
  ExperimentsBookingSimulationRoute: typeof ExperimentsBookingSimulationRouteWithChildren
  AiIndexRoute: typeof AiIndexRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  UiuxIndexRoute: typeof UiuxIndexRoute
  WebProjectsIndexRoute: typeof WebProjectsIndexRoute
  AiSlugExploreRoute: typeof AiSlugExploreRoute
  AiSlugProcessRoute: typeof AiSlugProcessRoute
  AiAiChatEngineAppRoute: typeof AiAiChatEngineAppRoute
  ToolsSlugLaunchRoute: typeof ToolsSlugLaunchRoute
  ToolsSlugProcessRoute: typeof ToolsSlugProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-games': {
      id: '/mini-games'
      path: '/mini-games'
      fullPath: '/mini-games'
      preLoaderRoute: typeof MiniGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-projects/': {
      id: '/web-projects/'
      path: '/web-projects'
      fullPath: '/web-projects/'
      preLoaderRoute: typeof WebProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uiux/': {
      id: '/uiux/'
      path: '/uiux'
      fullPath: '/uiux/'
      preLoaderRoute: typeof UiuxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/booking-simulation': {
      id: '/experiments/booking-simulation'
      path: '/experiments/booking-simulation'
      fullPath: '/experiments/booking-simulation'
      preLoaderRoute: typeof ExperimentsBookingSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/booking-platform': {
      id: '/experiments/booking-platform'
      path: '/experiments/booking-platform'
      fullPath: '/experiments/booking-platform'
      preLoaderRoute: typeof ExperimentsBookingPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/booking-platform/': {
      id: '/experiments/booking-platform/'
      path: '/'
      fullPath: '/experiments/booking-platform/'
      preLoaderRoute: typeof ExperimentsBookingPlatformIndexRouteImport
      parentRoute: typeof ExperimentsBookingPlatformRoute
    }
    '/tools/$slug/process': {
      id: '/tools/$slug/process'
      path: '/tools/$slug/process'
      fullPath: '/tools/$slug/process'
      preLoaderRoute: typeof ToolsSlugProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug/launch': {
      id: '/tools/$slug/launch'
      path: '/tools/$slug/launch'
      fullPath: '/tools/$slug/launch'
      preLoaderRoute: typeof ToolsSlugLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/booking-simulation/app': {
      id: '/experiments/booking-simulation/app'
      path: '/app'
      fullPath: '/experiments/booking-simulation/app'
      preLoaderRoute: typeof ExperimentsBookingSimulationAppRouteImport
      parentRoute: typeof ExperimentsBookingSimulationRoute
    }
    '/experiments/booking-platform/success': {
      id: '/experiments/booking-platform/success'
      path: '/success'
      fullPath: '/experiments/booking-platform/success'
      preLoaderRoute: typeof ExperimentsBookingPlatformSuccessRouteImport
      parentRoute: typeof ExperimentsBookingPlatformRoute
    }
    '/experiments/booking-platform/app': {
      id: '/experiments/booking-platform/app'
      path: '/app'
      fullPath: '/experiments/booking-platform/app'
      preLoaderRoute: typeof ExperimentsBookingPlatformAppRouteImport
      parentRoute: typeof ExperimentsBookingPlatformRoute
    }
    '/ai/ai-chat-engine/app': {
      id: '/ai/ai-chat-engine/app'
      path: '/ai/ai-chat-engine/app'
      fullPath: '/ai/ai-chat-engine/app'
      preLoaderRoute: typeof AiAiChatEngineAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$slug/process': {
      id: '/ai/$slug/process'
      path: '/ai/$slug/process'
      fullPath: '/ai/$slug/process'
      preLoaderRoute: typeof AiSlugProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$slug/explore': {
      id: '/ai/$slug/explore'
      path: '/ai/$slug/explore'
      fullPath: '/ai/$slug/explore'
      preLoaderRoute: typeof AiSlugExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExperimentsBookingPlatformRouteChildren {
  ExperimentsBookingPlatformAppRoute: typeof ExperimentsBookingPlatformAppRoute
  ExperimentsBookingPlatformSuccessRoute: typeof ExperimentsBookingPlatformSuccessRoute
  ExperimentsBookingPlatformIndexRoute: typeof ExperimentsBookingPlatformIndexRoute
}

const ExperimentsBookingPlatformRouteChildren: ExperimentsBookingPlatformRouteChildren =
  {
    ExperimentsBookingPlatformAppRoute: ExperimentsBookingPlatformAppRoute,
    ExperimentsBookingPlatformSuccessRoute:
      ExperimentsBookingPlatformSuccessRoute,
    ExperimentsBookingPlatformIndexRoute: ExperimentsBookingPlatformIndexRoute,
  }

const ExperimentsBookingPlatformRouteWithChildren =
  ExperimentsBookingPlatformRoute._addFileChildren(
    ExperimentsBookingPlatformRouteChildren,
  )

interface ExperimentsBookingSimulationRouteChildren {
  ExperimentsBookingSimulationAppRoute: typeof ExperimentsBookingSimulationAppRoute
}

const ExperimentsBookingSimulationRouteChildren: ExperimentsBookingSimulationRouteChildren =
  {
    ExperimentsBookingSimulationAppRoute: ExperimentsBookingSimulationAppRoute,
  }

const ExperimentsBookingSimulationRouteWithChildren =
  ExperimentsBookingSimulationRoute._addFileChildren(
    ExperimentsBookingSimulationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiniGamesRoute: MiniGamesRoute,
  SystemsRoute: SystemsRoute,
  ExperimentsBookingPlatformRoute: ExperimentsBookingPlatformRouteWithChildren,
  ExperimentsBookingSimulationRoute:
    ExperimentsBookingSimulationRouteWithChildren,
  AiIndexRoute: AiIndexRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  UiuxIndexRoute: UiuxIndexRoute,
  WebProjectsIndexRoute: WebProjectsIndexRoute,
  AiSlugExploreRoute: AiSlugExploreRoute,
  AiSlugProcessRoute: AiSlugProcessRoute,
  AiAiChatEngineAppRoute: AiAiChatEngineAppRoute,
  ToolsSlugLaunchRoute: ToolsSlugLaunchRoute,
  ToolsSlugProcessRoute: ToolsSlugProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
